version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - 'ambassador_db:/var/lib/mysql'
    ports:
      - 33066:3306

  redis:
    image: redis
    ports:
      - 6379:6379

  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: mailhog
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  ambassador_db:
    driver: local
